name: widget_toolbox
description: A toobox for flutter widgets.
version: 0.0.2
homepage: 
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^1.0.4
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

