name: widget_helpers
description: A toobox for flutter widgets.
version: 0.0.1
homepage: 
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.5+1
  get: ^4.6.5
  provider: ^6.0.0
  sensors_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

