name: Dart Helpers Library
description: A library for repetitive dart helpers
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
